name: Update Webpages

on:
  repository_dispatch:
    types: [oscovida-pr]

jobs:
  pr-webpage-gen:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Checkout oscovida/staging
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Checkout oscovida pr branch
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.client_payload.repository }}
          ref: ${{ github.event.client_payload.branch }}
          path: oscovida
      - name: Set up oscovida
        run: |
          pip install ./oscovida
      - name: Generate new reports
        run: |
          cp -r ./base ${{ github.event.client_payload.pr_no }}
          export WWWROOT=$(readlink -f ${{ github.event.client_payload.pr_no }})
          cd ./oscovida/tools/
          ln -s $WWWROOT ./wwwroot
          python3 -m report_generators.cli --debug --regions=all --workers=max --log-level=INFO --log-file=./wwwroot/report-gen.log
      - name: Generate individual plots
        run: |
          cd ./oscovida/tools/
          jupyter-nbconvert generate-individiual-plots.ipynb --execute
      - name: Update HTML pages
        run: |
          cd ./oscovida/tools/pelican
          make publish
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ${{ github.event.client_payload.pr_no }} --all
          git commit -m "Generated preview for PR ${{ github.event.client_payload.pr_no }} on $(date)" -a
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
